import type {
  Product,
  Donation,
  ImpactBadge,
  ImpactEvent,
  ShopOrder,
  ShopListing,
} from "./types";

// Generate relative ISO timestamps
const now = Date.now();
const hoursFromNow = (h: number) => new Date(now + h * 3600_000).toISOString();
const daysFromNow = (d: number) => new Date(now + d * 86_400_000).toISOString();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    shopId: "s1",
    shopName: "FreshMart Anna Nagar",
    shopDistanceKm: 0.8,
    shopRating: 4.6,
    name: "Amul Toned Milk 1L",
    description:
      "Sealed 1-litre toned milk pack. Stored refrigerated at 4°C. Suitable for tea, coffee, curd preparation and direct consumption.",
    category: "dairy",
    imageColor: "from-blue-50 to-cyan-100",
    imageEmoji: "milk",
    originalPrice: 80,
    discountedPrice: 30,
    quantity: 14,
    unit: "pack",
    bestBefore: daysFromNow(2),
    aiPredictedSafeUntil: daysFromNow(3),
    aiConfidence: 0.92,
    batchNo: "AMT-4421",
    storageType: "refrigerated",
    isAiMatch: true,
  },
  {
    id: "p2",
    shopId: "s2",
    shopName: "Daily Bread Bakery",
    shopDistanceKm: 1.4,
    shopRating: 4.8,
    name: "Whole Wheat Sandwich Bread",
    description:
      "Freshly baked whole wheat loaf, baked this morning. Soft texture, ideal for sandwiches and toast.",
    category: "bakery",
    imageColor: "from-amber-50 to-orange-100",
    imageEmoji: "bread",
    originalPrice: 50,
    discountedPrice: 15,
    quantity: 9,
    unit: "loaf",
    bestBefore: daysFromNow(1),
    aiPredictedSafeUntil: daysFromNow(2),
    aiConfidence: 0.88,
    batchNo: "DB-WW-220",
    storageType: "ambient",
    isAiMatch: true,
  },
  {
    id: "p3",
    shopId: "s1",
    shopName: "FreshMart Anna Nagar",
    shopDistanceKm: 0.8,
    shopRating: 4.6,
    name: "Mixed Vegetables Pack 1kg",
    description:
      "Assorted seasonal vegetables — tomato, carrot, beans, capsicum. Sourced this morning from wholesale market.",
    category: "vegetables",
    imageColor: "from-green-50 to-emerald-100",
    imageEmoji: "veg",
    originalPrice: 100,
    discountedPrice: 40,
    quantity: 6,
    unit: "pack",
    bestBefore: daysFromNow(2),
    aiPredictedSafeUntil: daysFromNow(2),
    aiConfidence: 0.95,
    batchNo: "VEG-MX-77",
    storageType: "ambient",
  },
  {
    id: "p4",
    shopId: "s3",
    shopName: "Snack Corner",
    shopDistanceKm: 2.1,
    shopRating: 4.4,
    name: "Haldiram Bhujia 200g",
    description:
      "Sealed pack of Haldiram bhujia. Crunchy savoury snack, perfect with tea.",
    category: "snacks",
    imageColor: "from-yellow-50 to-amber-100",
    imageEmoji: "snack",
    originalPrice: 60,
    discountedPrice: 20,
    quantity: 22,
    unit: "pack",
    bestBefore: daysFromNow(10),
    aiPredictedSafeUntil: daysFromNow(15),
    aiConfidence: 0.97,
    batchNo: "HAL-BJ-9912",
    storageType: "ambient",
  },
  {
    id: "p5",
    shopId: "s4",
    shopName: "Subiksha Foods",
    shopDistanceKm: 1.1,
    shopRating: 4.7,
    name: "Homemade Curd 500g",
    description:
      "Fresh set curd in sealed cup. Stored at 4°C. Best consumed within 2 days.",
    category: "dairy",
    imageColor: "from-slate-50 to-blue-100",
    imageEmoji: "curd",
    originalPrice: 45,
    discountedPrice: 18,
    quantity: 11,
    unit: "cup",
    bestBefore: daysFromNow(1),
    aiPredictedSafeUntil: daysFromNow(2),
    aiConfidence: 0.9,
    batchNo: "SUB-CD-441",
    storageType: "refrigerated",
    isAiMatch: true,
  },
  {
    id: "p6",
    shopId: "s2",
    shopName: "Daily Bread Bakery",
    shopDistanceKm: 1.4,
    shopRating: 4.8,
    name: "Cream Pastry (Pack of 4)",
    description:
      "Vanilla cream pastries baked this morning. Sealed pack of 4 pieces. Perfect for evening snack.",
    category: "bakery",
    imageColor: "from-pink-50 to-rose-100",
    imageEmoji: "pastry",
    originalPrice: 120,
    discountedPrice: 45,
    quantity: 4,
    unit: "pack",
    bestBefore: daysFromNow(1),
    aiPredictedSafeUntil: daysFromNow(1),
    aiConfidence: 0.85,
    batchNo: "DB-CP-118",
    storageType: "refrigerated",
  },
  {
    id: "p7",
    shopId: "s5",
    shopName: "Nila Fruits",
    shopDistanceKm: 0.6,
    shopRating: 4.5,
    name: "Bananas (1 dozen)",
    description:
      "Ripe bananas, slight spots on skin (ripeness indicator). Flesh is firm and sweet.",
    category: "fruits",
    imageColor: "from-yellow-50 to-amber-200",
    imageEmoji: "banana",
    originalPrice: 60,
    discountedPrice: 25,
    quantity: 8,
    unit: "dozen",
    bestBefore: daysFromNow(1),
    aiPredictedSafeUntil: daysFromNow(2),
    aiConfidence: 0.93,
    batchNo: "NIL-BN-55",
    storageType: "ambient",
  },
  {
    id: "p8",
    shopId: "s1",
    shopName: "FreshMart Anna Nagar",
    shopDistanceKm: 0.8,
    shopRating: 4.6,
    name: "Aashirvaad Atta 5kg",
    description:
      "Sealed 5kg pack of whole wheat flour. Suitable for chapati, roti, paratha.",
    category: "staples",
    imageColor: "from-orange-50 to-yellow-100",
    imageEmoji: "atta",
    originalPrice: 280,
    discountedPrice: 195,
    quantity: 3,
    unit: "pack",
    bestBefore: daysFromNow(45),
    aiPredictedSafeUntil: daysFromNow(60),
    aiConfidence: 0.99,
    batchNo: "AAS-AT-5-3344",
    storageType: "ambient",
  },
  {
    id: "p9",
    shopId: "s6",
    shopName: "Beverage World",
    shopDistanceKm: 1.8,
    shopRating: 4.3,
    name: "Real Mixed Fruit Juice 1L",
    description:
      "Sealed tetra pack. No preservatives. Refrigerate after opening.",
    category: "beverages",
    imageColor: "from-purple-50 to-fuchsia-100",
    imageEmoji: "juice",
    originalPrice: 110,
    discountedPrice: 40,
    quantity: 7,
    unit: "pack",
    bestBefore: daysFromNow(5),
    aiPredictedSafeUntil: daysFromNow(7),
    aiConfidence: 0.94,
    batchNo: "RL-MF-1L-88",
    storageType: "ambient",
  },
  {
    id: "p10",
    shopId: "s7",
    shopName: "Anjappar Kitchen",
    shopDistanceKm: 2.6,
    shopRating: 4.9,
    name: "Mixed Veg Biryani (Serves 2)",
    description:
      "Freshly cooked vegetable biryani from Anjappar. Prepared today afternoon. Sealed and refrigerated.",
    category: "cooked",
    imageColor: "from-orange-100 to-red-100",
    imageEmoji: "biryani",
    originalPrice: 220,
    discountedPrice: 80,
    quantity: 5,
    unit: "box",
    bestBefore: hoursFromNow(8),
    aiPredictedSafeUntil: hoursFromNow(10),
    aiConfidence: 0.81,
    batchNo: "AJ-BR-203",
    storageType: "refrigerated",
    isAiMatch: true,
  },
];

export const MOCK_DONATIONS: Donation[] = [
  {
    id: "d1",
    donorName: "Sri Mahal Marriage Hall",
    donorType: "marriage-hall",
    title: "Wedding Reception Surplus",
    description:
      "Vegetarian meals — rice, sambar, rasam, poriyal, curd. Hygienically packed in sealed boxes. Enough for ~80 people.",
    foodType: "cooked",
    quantity: 80,
    unit: "meals",
    servings: 80,
    pickupAddress: "Sri Mahal, Arcot Road, Vadapalani",
    pickupDistanceKm: 1.2,
    pickupWindowStart: hoursFromNow(0.5),
    pickupWindowEnd: hoursFromNow(2),
    expiryDeadline: hoursFromNow(3),
    aiFreshnessScore: 0.88,
    aiMatchScore: 92,
    status: "listed",
    imageColor: "from-emerald-100 to-teal-100",
  },
  {
    id: "d2",
    donorName: "VIT Hostel Mess",
    donorType: "hostel",
    title: "Hostel Dinner Extras",
    description:
      "Chapati, dal, mixed veg curry. Packed in 50 individual meal boxes. Pick up before 9 PM.",
    foodType: "cooked",
    quantity: 50,
    unit: "meals",
    servings: 50,
    pickupAddress: "VIT Hostel Block C, Vellore",
    pickupDistanceKm: 3.4,
    pickupWindowStart: hoursFromNow(1),
    pickupWindowEnd: hoursFromNow(2.5),
    expiryDeadline: hoursFromNow(4),
    aiFreshnessScore: 0.92,
    aiMatchScore: 78,
    status: "listed",
    imageColor: "from-amber-100 to-orange-100",
  },
  {
    id: "d3",
    donorName: "Saravana Bhavan",
    donorType: "restaurant",
    title: "End-of-Day Buffet Surplus",
    description:
      "Idli, vada, coconut chutney, sambar. ~30 servings. Sealed containers, refrigerated.",
    foodType: "cooked",
    quantity: 30,
    unit: "servings",
    servings: 30,
    pickupAddress: "Saravana Bhavan, T. Nagar",
    pickupDistanceKm: 2.0,
    pickupWindowStart: hoursFromNow(0.25),
    pickupWindowEnd: hoursFromNow(1.5),
    expiryDeadline: hoursFromNow(2),
    aiFreshnessScore: 0.95,
    aiMatchScore: 88,
    status: "listed",
    imageColor: "from-rose-100 to-pink-100",
  },
  {
    id: "d4",
    donorName: "Ramesh (Household)",
    donorType: "household",
    title: "Home-cooked Lemon Rice",
    description:
      "Lemon rice and curd rice, ~10 servings. Cooked this morning for a function, surplus remaining.",
    foodType: "cooked",
    quantity: 10,
    unit: "servings",
    servings: 10,
    pickupAddress: "8th Street, Anna Nagar West",
    pickupDistanceKm: 0.4,
    pickupWindowStart: hoursFromNow(0.5),
    pickupWindowEnd: hoursFromNow(3),
    expiryDeadline: hoursFromNow(5),
    aiFreshnessScore: 0.9,
    aiMatchScore: 95,
    status: "listed",
    imageColor: "from-yellow-100 to-lime-100",
  },
  {
    id: "d5",
    donorName: "TechConf 2025",
    donorType: "event",
    title: "Conference Lunch Surplus",
    description:
      "Boxed lunches — veg biryani, paneer curry, roti, sweets. ~60 boxes untouched. Pickup urgent.",
    foodType: "cooked",
    quantity: 60,
    unit: "boxes",
    servings: 60,
    pickupAddress: "Chennai Trade Centre, Nandambakkam",
    pickupDistanceKm: 5.1,
    pickupWindowStart: hoursFromNow(0.5),
    pickupWindowEnd: hoursFromNow(2),
    expiryDeadline: hoursFromNow(2.5),
    aiFreshnessScore: 0.86,
    aiMatchScore: 71,
    status: "listed",
    imageColor: "from-sky-100 to-cyan-100",
  },
];

export const MOCK_BADGES: ImpactBadge[] = [
  {
    id: "b1",
    name: "First Rescue",
    description: "Complete your first food rescue",
    icon: "Heart",
    unlocked: true,
  },
  {
    id: "b2",
    name: "Saver Streak",
    description: "Rescue food 7 days in a row",
    icon: "Flame",
    unlocked: true,
  },
  {
    id: "b3",
    name: "Carbon Cutter",
    description: "Prevent 50kg of CO2 emissions",
    icon: "Leaf",
    unlocked: true,
  },
  {
    id: "b4",
    name: "Community Hero",
    description: "Volunteer for 10 pickups",
    icon: "Users",
    unlocked: false,
    progress: 70,
  },
  {
    id: "b5",
    name: "Century Saver",
    description: "Save 100 meals from waste",
    icon: "Award",
    unlocked: false,
    progress: 84,
  },
  {
    id: "b6",
    name: "Platinum Patron",
    description: "Reach Platinum impact level",
    icon: "Crown",
    unlocked: false,
    progress: 45,
  },
];

export const MOCK_IMPACT_EVENTS: ImpactEvent[] = [
  {
    id: "e1",
    type: "rescue",
    label: "Rescued Wedding Reception Surplus",
    mealsSaved: 80,
    co2SavedKg: 32,
    moneySaved: 0,
    points: 240,
    timestamp: hoursAgo(2),
  },
  {
    id: "e2",
    type: "purchase",
    label: "Bought Amul Toned Milk 1L",
    mealsSaved: 4,
    co2SavedKg: 1.2,
    moneySaved: 50,
    points: 12,
    timestamp: hoursAgo(8),
  },
  {
    id: "e3",
    type: "volunteer",
    label: "Volunteer pickup completed — T. Nagar",
    mealsSaved: 30,
    co2SavedKg: 12,
    moneySaved: 0,
    points: 90,
    timestamp: hoursAgo(26),
  },
  {
    id: "e4",
    type: "purchase",
    label: "Bought Mixed Vegetables Pack",
    mealsSaved: 6,
    co2SavedKg: 2.4,
    moneySaved: 60,
    points: 18,
    timestamp: hoursAgo(30),
  },
  {
    id: "e5",
    type: "donate",
    label: "Donated Home-cooked Lemon Rice",
    mealsSaved: 10,
    co2SavedKg: 4,
    moneySaved: 0,
    points: 30,
    timestamp: hoursAgo(48),
  },
];

export const MOCK_MONTHLY_IMPACT = [
  { day: "Mon", meals: 12, co2: 4.8 },
  { day: "Tue", meals: 18, co2: 7.2 },
  { day: "Wed", meals: 24, co2: 9.6 },
  { day: "Thu", meals: 15, co2: 6.0 },
  { day: "Fri", meals: 32, co2: 12.8 },
  { day: "Sat", meals: 45, co2: 18.0 },
  { day: "Sun", meals: 38, co2: 15.2 },
];

export const MOCK_SHOP_ORDERS: ShopOrder[] = [
  {
    id: "o1",
    customerName: "Priya S.",
    items: [
      { name: "Amul Toned Milk 1L", qty: 2, price: 30 },
      { name: "Mixed Vegetables Pack", qty: 1, price: 40 },
    ],
    total: 100,
    status: "new",
    placedAt: hoursAgo(0.1),
    distance: 0.8,
  },
  {
    id: "o2",
    customerName: "Karthik R.",
    items: [{ name: "Whole Wheat Sandwich Bread", qty: 2, price: 15 }],
    total: 30,
    status: "new",
    placedAt: hoursAgo(0.25),
    distance: 1.4,
  },
  {
    id: "o3",
    customerName: "Lakshmi M.",
    items: [
      { name: "Aashirvaad Atta 5kg", qty: 1, price: 195 },
      { name: "Haldiram Bhujia 200g", qty: 2, price: 20 },
    ],
    total: 235,
    status: "accepted",
    placedAt: hoursAgo(0.5),
    distance: 2.1,
  },
  {
    id: "o4",
    customerName: "Mohammed A.",
    items: [{ name: "Cream Pastry (Pack of 4)", qty: 1, price: 45 }],
    total: 45,
    status: "completed",
    placedAt: hoursAgo(2),
    distance: 0.6,
  },
];

export const MOCK_SHOP_LISTINGS: ShopListing[] = [
  {
    id: "l1",
    name: "Amul Toned Milk 1L",
    category: "dairy",
    qtyLeft: 14,
    originalPrice: 80,
    discountedPrice: 30,
    discountPct: 63,
    daysToExpiry: 2,
    imageColor: "from-blue-50 to-cyan-100",
    soldToday: 6,
    revenueToday: 180,
  },
  {
    id: "l2",
    name: "Mixed Vegetables Pack 1kg",
    category: "vegetables",
    qtyLeft: 6,
    originalPrice: 100,
    discountedPrice: 40,
    discountPct: 60,
    daysToExpiry: 2,
    imageColor: "from-green-50 to-emerald-100",
    soldToday: 4,
    revenueToday: 160,
  },
  {
    id: "l3",
    name: "Aashirvaad Atta 5kg",
    category: "staples",
    qtyLeft: 3,
    originalPrice: 280,
    discountedPrice: 195,
    discountPct: 30,
    daysToExpiry: 45,
    imageColor: "from-orange-50 to-yellow-100",
    soldToday: 2,
    revenueToday: 390,
  },
  {
    id: "l4",
    name: "Bananas (1 dozen)",
    category: "fruits",
    qtyLeft: 8,
    originalPrice: 60,
    discountedPrice: 25,
    discountPct: 58,
    daysToExpiry: 1,
    imageColor: "from-yellow-50 to-amber-200",
    soldToday: 9,
    revenueToday: 225,
  },
];

export const ONBOARDING_SLIDES = [
  {
    title: "Rescue food, save money",
    subtitle:
      "Buy near-expiry groceries at up to 70% off. Same product, fraction of the price.",
    gradient: "from-emerald-500 via-emerald-600 to-teal-700",
    accentIcon: "ShoppingBasket",
  },
  {
    title: "Donate surplus, feed communities",
    subtitle:
      "Marriage halls, restaurants and households list surplus food. NGOs and volunteers pick it up before it spoils.",
    gradient: "from-amber-500 via-orange-500 to-red-500",
    accentIcon: "HeartHandshake",
  },
  {
    title: "AI-powered impact",
    subtitle:
      "Smart matching, expiry prediction, route optimisation. Every rescue earns impact points and reduces CO2.",
    gradient: "from-teal-500 via-emerald-600 to-emerald-800",
    accentIcon: "Sparkles",
  },
];

export const ROLE_CARDS = [
  {
    role: "user" as const,
    title: "Normal User",
    description: "Buy affordable groceries, donate food, volunteer",
    icon: "ShoppingBag",
    accent: "from-emerald-500 to-teal-600",
  },
  {
    role: "shop" as const,
    title: "Shop Owner",
    description: "Recover losses, sell near-expiry products",
    icon: "Store",
    accent: "from-amber-500 to-orange-600",
  },
  {
    role: "ngo" as const,
    title: "NGO",
    description: "Receive donations, coordinate volunteers",
    icon: "HeartHandshake",
    accent: "from-rose-500 to-red-600",
  },
  {
    role: "volunteer" as const,
    title: "Volunteer",
    description: "Pickup & deliver food, earn impact points",
    icon: "Bike",
    accent: "from-sky-500 to-cyan-600",
  },
];
